/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (MegaMan8)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800C0B3Cu
#define func_800C0B3C BootEntry  /* alias */
